apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: toluna-devops
  name: toluna-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toluna-devops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toluna-devops
    spec:
      containers:
      - image: fadizaboura/toluna-devops:1
        imagePullPolicy: Always
        name: toluna-devops
        ports:
          - containerPort: 5000


