apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: toluna-devops
  name: toluna-devops
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: toluna-devops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toluna-devops
    spec:
      containers:
      - image: fadizaboura/toluna-devops:1
        imagePullPolicy: Always
        name: toluna-devops
        ports:
          - containerPort: 5000
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
